### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by aftabnaveed** [tideways/php-profiler-extension#30]
Is your extension supported on HHVM?

**Comment by beberlei** [comment]
No, and we have scraped plans to support HHVM going forwards, because of PHP 7 its usage numbers and requests for supporting it further have decreased a lot. Sorry.

You can use the Composer package [tideways/profiler](https://github.com/tideways/profiler) to get callgraph profiling support working. See the docs for installation: https://tideways.io/profiler/docs/setup/hhvm 

But we don't support automatic transaction detection, error tracking and timeline profiling support in HHVM.
